Warnings for new events
grisp/rebar3_grisp pull request #72
Opened 2022-05-27 14:18 UTC by ziopio

2022-05-27 14:20 UTC, ziopio commented
![](https://github.trello.services/images/mini-trello-icon.png) ['rebar3 grisp deploy' cannot work without internet](https://trello.com/c/Y8BtngIu/119-rebar3-grisp-deploy-cannot-work-without-internet)

2022-05-30 14:07 UTC, eproxus commented on src/rebar3_grisp_util.erl
> -    rebar_utils:sh(Command, Args ++ [abort_on_error]).
We probably want this to be the default for a lot of other tasks. There should be a flag to disable it only for the commands that really need it.

2022-05-30 14:08 UTC, eproxus requested changes

2022-05-30 14:08 UTC, eproxus commented on src/rebar3_grisp_util.erl
> -    rebar_utils:sh(Command, Args ++ [abort_on_error]).
We probably want this to be the default for a lot of other tasks. There should be a flag to disable it only for the commands that really need it.

2022-06-07 09:17 UTC, eproxus approved these changes

2022-06-07 09:18 UTC, merged